name: Check Ansible Debian stable
description: Check ansible role with the Debian stable docker container
author: L3D <l3d@c3woc.de>

inputs: 
  targets:
    description: |
      Paths to the ansible role you want to be tested.
      For example './' or 'roles/my_role/'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    TARGETS: ${{ inputs.targets }}
